image: python:3.7

stages:
  - test

before_script:
  - date
  - pwd
  - ls

pytest:
  stage: test
  script:
    - python3 -m pip install -r requirements.txt
    - python3 -m pytest workoutizer/wizer/tests -v

django:
  stage: test
  script:
    - python3 -m pip install -r requirements.txt
    - python3 workoutizer/manage.py collectstatic --noinput
    - python3 workoutizer/manage.py check
    - python3 workoutizer/manage.py makemigrations
    - python3 workoutizer/manage.py migrate
    - python3 workoutizer/manage.py loaddata wizer.settings.json
