image: python:3.7

stages:
  - test

before_script:
  - date
  - python3 -m pip install -r requirements.txt

pytest:
  stage: test
  script:
    - cd workoutizer
    - python3 -m pytest wizer/tests/unit_tests -v
    - python3 -m pytest wizer/tests/integration_tests -v
#    - python3 -m pytest wizer/tests/browser_tests -v   # not used since webdriver does not work in CI

django:
  stage: test
  script:
    - cd workoutizer
    - python3 manage.py collectstatic --noinput
    - python3 manage.py check
    - python3 manage.py makemigrations
    - python3 manage.py migrate
