image: python:3.7

stages:
  - test

before_script:
  - date
  - python3 -m pip install -r requirements.txt

pytest:
  stage: test
  script:
    - cd workoutizer
    - python3 -m pytest -v

django:
  stage: test
  script:
    - cd workoutizer
    - python3 manage.py collectstatic --noinput
    - python3 manage.py check
    - python3 manage.py makemigrations
    - python3 manage.py migrate
    - python3 manage.py test -v 2
