image: python:3.7

stages:
  - test

before_script:
  - date
  - pwd
  - ls


### test

pytest:
  stage: test
  script:
    - python3 -m pip install requirements.txt
    - python3 -m pytest workoutizer/wizer/tests -v